package com.afis.cloud.entities.dao.auth;

import com.afis.cloud.db.PageResult;
import com.afis.cloud.entities.model.auth.AppUser;
import com.afis.cloud.entities.model.auth.AppUserExample;
import com.afis.cloud.entities.model.auth.AppUserSelective;
import com.ibatis.sqlmap.client.event.RowHandler;
import java.sql.SQLException;
import java.util.List;

public interface AppUserDAO {
    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    int countByExample(AppUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    int deleteByExample(AppUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    int deleteByPrimaryKey(long id) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Deprecated
    long insert(AppUser record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    long insert(AppUserSelective record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    int selectByExample(AppUserExample example, RowHandler<AppUser> rowHandler) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    List<AppUser> selectByExample(AppUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    PageResult<AppUser> selectByExample(AppUserExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    AppUser selectByPrimaryKey(long id) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    int updateByExample(AppUserSelective record, AppUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Deprecated
    int updateByExample(AppUser record, AppUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    int updateByPrimaryKey(AppUserSelective record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Deprecated
    int updateByPrimaryKey(AppUser record) throws SQLException;
}