package com.afis.cloud.entities.dao.auth;

import com.afis.cloud.db.PageResult;
import com.afis.cloud.entities.model.auth.Function;
import com.afis.cloud.entities.model.auth.FunctionExample;
import com.afis.cloud.entities.model.auth.FunctionSelective;
import com.ibatis.sqlmap.client.event.RowHandler;
import java.sql.SQLException;
import java.util.List;

public interface FunctionDAO {
    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    int countByExample(FunctionExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    int deleteByExample(FunctionExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    int deleteByPrimaryKey(long id) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Deprecated
    long insert(Function record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    long insert(FunctionSelective record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    int selectByExample(FunctionExample example, RowHandler<Function> rowHandler) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    List<Function> selectByExample(FunctionExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    PageResult<Function> selectByExample(FunctionExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    Function selectByPrimaryKey(long id) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    int updateByExample(FunctionSelective record, FunctionExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Deprecated
    int updateByExample(Function record, FunctionExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    int updateByPrimaryKey(FunctionSelective record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Deprecated
    int updateByPrimaryKey(Function record) throws SQLException;
}