package com.afis.cloud.entities.dao.auth;

import com.afis.cloud.db.PageResult;
import com.afis.cloud.entities.model.auth.LoginLog;
import com.afis.cloud.entities.model.auth.LoginLogExample;
import com.afis.cloud.entities.model.auth.LoginLogSelective;
import com.ibatis.sqlmap.client.event.RowHandler;
import java.sql.SQLException;
import java.util.List;

public interface LoginLogDAO {
    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    int countByExample(LoginLogExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    int deleteByExample(LoginLogExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    int deleteByPrimaryKey(long id) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    @Deprecated
    long insert(LoginLog record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    long insert(LoginLogSelective record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    int selectByExample(LoginLogExample example, RowHandler<LoginLog> rowHandler) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    List<LoginLog> selectByExample(LoginLogExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    PageResult<LoginLog> selectByExample(LoginLogExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    LoginLog selectByPrimaryKey(long id) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    int updateByExample(LoginLogSelective record, LoginLogExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    @Deprecated
    int updateByExample(LoginLog record, LoginLogExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    int updateByPrimaryKey(LoginLogSelective record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    @Deprecated
    int updateByPrimaryKey(LoginLog record) throws SQLException;
}