package com.afis.cloud.entities.dao.auth;

import com.afis.cloud.db.PageResult;
import com.afis.cloud.entities.model.auth.OnlineUser;
import com.afis.cloud.entities.model.auth.OnlineUserExample;
import com.afis.cloud.entities.model.auth.OnlineUserSelective;
import com.ibatis.sqlmap.client.event.RowHandler;
import java.sql.SQLException;
import java.util.List;

public interface OnlineUserDAO {
    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    int countByExample(OnlineUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    int deleteByExample(OnlineUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    int deleteByPrimaryKey(String loginKey) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Deprecated
    void insert(OnlineUser record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    void insert(OnlineUserSelective record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    int selectByExample(OnlineUserExample example, RowHandler<OnlineUser> rowHandler) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    List<OnlineUser> selectByExample(OnlineUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    PageResult<OnlineUser> selectByExample(OnlineUserExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    OnlineUser selectByPrimaryKey(String loginKey) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    int updateByExample(OnlineUserSelective record, OnlineUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Deprecated
    int updateByExample(OnlineUser record, OnlineUserExample example) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    int updateByPrimaryKey(OnlineUserSelective record) throws SQLException;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Deprecated
    int updateByPrimaryKey(OnlineUser record) throws SQLException;
}