package com.afis.cloud.entities.dao.impl.auth;

import com.afis.cloud.db.PageResult;
import com.afis.cloud.db.TurnPage;
import com.afis.cloud.entities.dao.auth.AppUserDAO;
import com.afis.cloud.entities.model.auth.AppUser;
import com.afis.cloud.entities.model.auth.AppUserExample;
import com.afis.cloud.entities.model.auth.AppUserSelective;
import com.ibatis.sqlmap.client.SqlMapClient;
import com.ibatis.sqlmap.client.event.RowHandler;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AppUserDAOImpl implements AppUserDAO {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    protected SqlMapClient sqlMapClient;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public AppUserDAOImpl(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public int countByExample(AppUserExample example) throws SQLException {
        return (Integer)sqlMapClient.queryForObject("T_A_APP_USER.sacoolbuildergenerated_countByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public int deleteByExample(AppUserExample example) throws SQLException {
        return sqlMapClient.delete("T_A_APP_USER.sacoolbuildergenerated_deleteByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public int deleteByPrimaryKey(long id) throws SQLException {
        return sqlMapClient.delete("T_A_APP_USER.sacoolbuildergenerated_deleteByPrimaryKey", id);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public long insert(AppUser record) throws SQLException {
        Object newKey = sqlMapClient.insert("T_A_APP_USER.sacoolbuildergenerated_insert", record);
        return ((Long) newKey).longValue();
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public long insert(AppUserSelective record) throws SQLException {
        Object newKey = sqlMapClient.insert("T_A_APP_USER.sacoolbuildergenerated_insertSelective", record);
        return ((Long)newKey).longValue();
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public int selectByExample(AppUserExample example, RowHandler<AppUser> rowHandler) throws SQLException {
        return sqlMapClient.queryWithRowHandler("T_A_APP_USER.sacoolbuildergenerated_selectByExample", example, rowHandler);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    @SuppressWarnings("unchecked")
    public List<AppUser> selectByExample(AppUserExample example) throws SQLException {
        return sqlMapClient.queryForList("T_A_APP_USER.sacoolbuildergenerated_selectByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public PageResult<AppUser> selectByExample(AppUserExample example, int start, int limit) throws SQLException {
        return new TurnPage(sqlMapClient).selectByExampleWidthPageResult("T_A_APP_USER.sacoolbuildergenerated_selectByExample", "T_A_APP_USER.sacoolbuildergenerated_countByExample", example, start, limit);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public AppUser selectByPrimaryKey(long id) throws SQLException {
        return (AppUser)sqlMapClient.queryForObject("T_A_APP_USER.sacoolbuildergenerated_selectByPrimaryKey", id);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public int updateByExample(AppUserSelective record, AppUserExample example) throws SQLException {
        Map<String, Object> parms = new HashMap<String, Object>();
        parms.put("record", record);
        parms.put("oredCriteria", example == null ? null : example.getOredCriteria());
        return sqlMapClient.update("T_A_APP_USER.sacoolbuildergenerated_updateByExampleSelective", parms);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public int updateByExample(AppUser record, AppUserExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("T_A_APP_USER.sacoolbuildergenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    public int updateByPrimaryKey(AppUserSelective record) throws SQLException {
        return sqlMapClient.update("T_A_APP_USER.sacoolbuildergenerated_updateByPrimaryKeySelective", record);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public int updateByPrimaryKey(AppUser record) throws SQLException {
        int rows = sqlMapClient.update("T_A_APP_USER.sacoolbuildergenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by www.sacool.com iBATIS builder.
     * <br>This class corresponds to the database table T_A_APP_USER
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    @Deprecated
    static class UpdateByExampleParms extends AppUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, AppUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}