package com.afis.cloud.entities.dao.impl.auth;

import com.afis.cloud.db.PageResult;
import com.afis.cloud.db.TurnPage;
import com.afis.cloud.entities.dao.auth.FunctionDAO;
import com.afis.cloud.entities.model.auth.Function;
import com.afis.cloud.entities.model.auth.FunctionExample;
import com.afis.cloud.entities.model.auth.FunctionSelective;
import com.ibatis.sqlmap.client.SqlMapClient;
import com.ibatis.sqlmap.client.event.RowHandler;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FunctionDAOImpl implements FunctionDAO {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    protected SqlMapClient sqlMapClient;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public FunctionDAOImpl(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public int countByExample(FunctionExample example) throws SQLException {
        return (Integer)sqlMapClient.queryForObject("T_AI_FUNCTION.sacoolbuildergenerated_countByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public int deleteByExample(FunctionExample example) throws SQLException {
        return sqlMapClient.delete("T_AI_FUNCTION.sacoolbuildergenerated_deleteByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public int deleteByPrimaryKey(long id) throws SQLException {
        return sqlMapClient.delete("T_AI_FUNCTION.sacoolbuildergenerated_deleteByPrimaryKey", id);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public long insert(Function record) throws SQLException {
        Object newKey = sqlMapClient.insert("T_AI_FUNCTION.sacoolbuildergenerated_insert", record);
        return ((Long) newKey).longValue();
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public long insert(FunctionSelective record) throws SQLException {
        Object newKey = sqlMapClient.insert("T_AI_FUNCTION.sacoolbuildergenerated_insertSelective", record);
        return ((Long)newKey).longValue();
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public int selectByExample(FunctionExample example, RowHandler<Function> rowHandler) throws SQLException {
        return sqlMapClient.queryWithRowHandler("T_AI_FUNCTION.sacoolbuildergenerated_selectByExample", example, rowHandler);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    @SuppressWarnings("unchecked")
    public List<Function> selectByExample(FunctionExample example) throws SQLException {
        return sqlMapClient.queryForList("T_AI_FUNCTION.sacoolbuildergenerated_selectByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public PageResult<Function> selectByExample(FunctionExample example, int start, int limit) throws SQLException {
        return new TurnPage(sqlMapClient).selectByExampleWidthPageResult("T_AI_FUNCTION.sacoolbuildergenerated_selectByExample", "T_AI_FUNCTION.sacoolbuildergenerated_countByExample", example, start, limit);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public Function selectByPrimaryKey(long id) throws SQLException {
        return (Function)sqlMapClient.queryForObject("T_AI_FUNCTION.sacoolbuildergenerated_selectByPrimaryKey", id);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public int updateByExample(FunctionSelective record, FunctionExample example) throws SQLException {
        Map<String, Object> parms = new HashMap<String, Object>();
        parms.put("record", record);
        parms.put("oredCriteria", example == null ? null : example.getOredCriteria());
        return sqlMapClient.update("T_AI_FUNCTION.sacoolbuildergenerated_updateByExampleSelective", parms);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public int updateByExample(Function record, FunctionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("T_AI_FUNCTION.sacoolbuildergenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    public int updateByPrimaryKey(FunctionSelective record) throws SQLException {
        return sqlMapClient.update("T_AI_FUNCTION.sacoolbuildergenerated_updateByPrimaryKeySelective", record);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public int updateByPrimaryKey(Function record) throws SQLException {
        int rows = sqlMapClient.update("T_AI_FUNCTION.sacoolbuildergenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by www.sacool.com iBATIS builder.
     * <br>This class corresponds to the database table T_AI_FUNCTION
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    @Deprecated
    static class UpdateByExampleParms extends FunctionExample {
        private Object record;

        public UpdateByExampleParms(Object record, FunctionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}