package com.afis.cloud.entities.dao.impl.auth;

import com.afis.cloud.db.PageResult;
import com.afis.cloud.db.TurnPage;
import com.afis.cloud.entities.dao.auth.OnlineUserDAO;
import com.afis.cloud.entities.model.auth.OnlineUser;
import com.afis.cloud.entities.model.auth.OnlineUserExample;
import com.afis.cloud.entities.model.auth.OnlineUserSelective;
import com.ibatis.sqlmap.client.SqlMapClient;
import com.ibatis.sqlmap.client.event.RowHandler;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OnlineUserDAOImpl implements OnlineUserDAO {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    protected SqlMapClient sqlMapClient;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public OnlineUserDAOImpl(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public int countByExample(OnlineUserExample example) throws SQLException {
        return (Integer)sqlMapClient.queryForObject("T_A_ONLINE_USER.sacoolbuildergenerated_countByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public int deleteByExample(OnlineUserExample example) throws SQLException {
        return sqlMapClient.delete("T_A_ONLINE_USER.sacoolbuildergenerated_deleteByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public int deleteByPrimaryKey(String loginKey) throws SQLException {
        return sqlMapClient.delete("T_A_ONLINE_USER.sacoolbuildergenerated_deleteByPrimaryKey", loginKey);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public void insert(OnlineUser record) throws SQLException {
        sqlMapClient.insert("T_A_ONLINE_USER.sacoolbuildergenerated_insert", record);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public void insert(OnlineUserSelective record) throws SQLException {
        sqlMapClient.insert("T_A_ONLINE_USER.sacoolbuildergenerated_insertSelective", record);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public int selectByExample(OnlineUserExample example, RowHandler<OnlineUser> rowHandler) throws SQLException {
        return sqlMapClient.queryWithRowHandler("T_A_ONLINE_USER.sacoolbuildergenerated_selectByExample", example, rowHandler);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    @SuppressWarnings("unchecked")
    public List<OnlineUser> selectByExample(OnlineUserExample example) throws SQLException {
        return sqlMapClient.queryForList("T_A_ONLINE_USER.sacoolbuildergenerated_selectByExample", example);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public PageResult<OnlineUser> selectByExample(OnlineUserExample example, int start, int limit) throws SQLException {
        return new TurnPage(sqlMapClient).selectByExampleWidthPageResult("T_A_ONLINE_USER.sacoolbuildergenerated_selectByExample", "T_A_ONLINE_USER.sacoolbuildergenerated_countByExample", example, start, limit);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public OnlineUser selectByPrimaryKey(String loginKey) throws SQLException {
        return (OnlineUser)sqlMapClient.queryForObject("T_A_ONLINE_USER.sacoolbuildergenerated_selectByPrimaryKey", loginKey);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public int updateByExample(OnlineUserSelective record, OnlineUserExample example) throws SQLException {
        Map<String, Object> parms = new HashMap<String, Object>();
        parms.put("record", record);
        parms.put("oredCriteria", example == null ? null : example.getOredCriteria());
        return sqlMapClient.update("T_A_ONLINE_USER.sacoolbuildergenerated_updateByExampleSelective", parms);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public int updateByExample(OnlineUser record, OnlineUserExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("T_A_ONLINE_USER.sacoolbuildergenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    public int updateByPrimaryKey(OnlineUserSelective record) throws SQLException {
        return sqlMapClient.update("T_A_ONLINE_USER.sacoolbuildergenerated_updateByPrimaryKeySelective", record);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Override
    @Deprecated
    public int updateByPrimaryKey(OnlineUser record) throws SQLException {
        int rows = sqlMapClient.update("T_A_ONLINE_USER.sacoolbuildergenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by www.sacool.com iBATIS builder.
     * <br>This class corresponds to the database table T_A_ONLINE_USER
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    @Deprecated
    static class UpdateByExampleParms extends OnlineUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, OnlineUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}