package com.afis.cloud.entities.model.auth;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

public class AppFunctionExample {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private LinkedHashMap<String, String> orderByClauseMap;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String orderByClause;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected String alias;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample() {
        oredCriteria = new ArrayList<Criteria>();
        orderByClauseMap = new LinkedHashMap<String, String>();
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     * @param alias The dynamic alias of the table.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample(String alias) {
        this();
        this.alias = alias;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     * @param example Another example will be copied to this.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected AppFunctionExample(AppFunctionExample example) {
        this.orderByClauseMap = new LinkedHashMap<String, String>(example.orderByClauseMap);
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     * @param example Another example will be copied to this.
     * @param alias The dynamic alias of the table.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected AppFunctionExample(AppFunctionExample example, String alias) {
        this(example);
        this.alias = alias;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample orderById(String direction) {
        return this.orderBy("ID", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderById() {
        return this.removeOrderBy("ID");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample orderByAppId(String direction) {
        return this.orderBy("APP_ID", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByAppId() {
        return this.removeOrderBy("APP_ID");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample orderByFunctionId(String direction) {
        return this.orderBy("FUNCTION_ID", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByFunctionId() {
        return this.removeOrderBy("FUNCTION_ID");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample orderByOperateAppId(String direction) {
        return this.orderBy("OPERATE_APP_ID", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByOperateAppId() {
        return this.removeOrderBy("OPERATE_APP_ID");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample orderByOperator(String direction) {
        return this.orderBy("OPERATOR", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByOperator() {
        return this.removeOrderBy("OPERATOR");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample orderByOperateTime(String direction) {
        return this.orderBy("OPERATE_TIME", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByOperateTime() {
        return this.removeOrderBy("OPERATE_TIME");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public AppFunctionExample orderBy(String field, String direction) {
        boolean have = orderByClauseMap.containsKey(field);
        String old = orderByClauseMap.put(field, direction);
        if(have && (old == null ? direction != null : !old.equals(direction))) orderByClause = null;
        return this;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderBy(String field) {
        if(orderByClauseMap.containsKey(field)){
            orderByClause = null;
            return orderByClauseMap.remove(field);
        }
        return null;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void clearOrderByClause() {
        if(!orderByClauseMap.isEmpty()){
            orderByClause = null;
            orderByClauseMap.clear();
        }
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getOrderByClause() {
        if(orderByClause == null){
            StringBuilder sb = new StringBuilder();
            Iterator<Entry<String, String>> iterator = orderByClauseMap.entrySet().iterator();
            boolean aliasEmpty = this.alias == null || this.alias.isEmpty();
            while(iterator.hasNext()){
                Entry<String, String> entry = iterator.next();
                String key = entry.getKey();
                String value = entry.getValue();
                boolean keyEmpty = key == null || key.isEmpty();
                boolean valueEmpty = value == null || value.isEmpty();
                if(!keyEmpty){
                    if(!aliasEmpty){
                        sb.append(this.alias);
                        sb.append(".");
                    }
                    sb.append(entry.getKey());
                }
                if(!valueEmpty){
                    if(!keyEmpty) sb.append(" ");
                    sb.append(entry.getValue());
                }
                if(!keyEmpty || !valueEmpty) sb.append(", ");
            }
            if(sb.length() != 0) sb.setLength(sb.length() - 2);
            orderByClause = sb.toString();
        }
        return orderByClause;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     * @param alias The dynamic alias of the table.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setAlias(String alias) {
        this.alias = alias;
        orderByClause = null;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if(oredCriteria.size() == 0) oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected Criteria createCriteriaInternal() {
        return new Criteria();
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void clearOredCriteria() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by www.sacool.com iBATIS builder.
     * <br>This class corresponds to the database table T_A_APP_FUNCTION
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public static class Criteria {
        protected List<String> criteriaWithSqlSnippetValue;

        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithSqlSnippetValue = new ArrayList<String>();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithSqlSnippetValue.size() > 0
                || criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithSqlSnippetValue() {
            return criteriaWithSqlSnippetValue;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            List<Map<String, Object>> list = null;
            String valueKey = "value";
            if(value.getClass().isArray()) {
                if(Array.getLength(value) == 0) throw new RuntimeException("Value array for " + property + " cannot be empty");
                list = criteriaWithListValue;
                valueKey = "values";
            } else list = criteriaWithSingleValue;
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put(valueKey, value);
            list.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSQLSnippet(String sqlSnippet) {
            if(sqlSnippet == null){
                throw new RuntimeException("Value for sqlSnippet cannot be null");
            }
            criteriaWithSqlSnippetValue.add(sqlSnippet);
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID IS NULL");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID IS NOT NULL");
            return this;
        }

        public Criteria andIdEqualTo(long value) {
            addCriterion("ID =", new Long(value), "id");
            return this;
        }

        public Criteria andIdNotEqualTo(long value) {
            addCriterion("ID <>", new Long(value), "id");
            return this;
        }

        public Criteria andIdGreaterThan(long value) {
            addCriterion("ID >", new Long(value), "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(long value) {
            addCriterion("ID >=", new Long(value), "id");
            return this;
        }

        public Criteria andIdLessThan(long value) {
            addCriterion("ID <", new Long(value), "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(long value) {
            addCriterion("ID <=", new Long(value), "id");
            return this;
        }

        public Criteria andIdIn(long[] values) {
            addCriterion("ID IN", values, "id");
            return this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID IN", values, "id");
            return this;
        }

        public Criteria andIdNotIn(long[] values) {
            addCriterion("ID NOT IN", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID NOT IN", values, "id");
            return this;
        }

        public Criteria andIdBetween(long value1, long value2) {
            addCriterion("ID BETWEEN", new Long(value1), new Long(value2), "id");
            return this;
        }

        public Criteria andIdNotBetween(long value1, long value2) {
            addCriterion("ID NOT BETWEEN", new Long(value1), new Long(value2), "id");
            return this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("APP_ID IS NULL");
            return this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("APP_ID IS NOT NULL");
            return this;
        }

        public Criteria andAppIdEqualTo(long value) {
            addCriterion("APP_ID =", new Long(value), "appId");
            return this;
        }

        public Criteria andAppIdNotEqualTo(long value) {
            addCriterion("APP_ID <>", new Long(value), "appId");
            return this;
        }

        public Criteria andAppIdGreaterThan(long value) {
            addCriterion("APP_ID >", new Long(value), "appId");
            return this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(long value) {
            addCriterion("APP_ID >=", new Long(value), "appId");
            return this;
        }

        public Criteria andAppIdLessThan(long value) {
            addCriterion("APP_ID <", new Long(value), "appId");
            return this;
        }

        public Criteria andAppIdLessThanOrEqualTo(long value) {
            addCriterion("APP_ID <=", new Long(value), "appId");
            return this;
        }

        public Criteria andAppIdIn(long[] values) {
            addCriterion("APP_ID IN", values, "appId");
            return this;
        }

        public Criteria andAppIdIn(List<Long> values) {
            addCriterion("APP_ID IN", values, "appId");
            return this;
        }

        public Criteria andAppIdNotIn(long[] values) {
            addCriterion("APP_ID NOT IN", values, "appId");
            return this;
        }

        public Criteria andAppIdNotIn(List<Long> values) {
            addCriterion("APP_ID NOT IN", values, "appId");
            return this;
        }

        public Criteria andAppIdBetween(long value1, long value2) {
            addCriterion("APP_ID BETWEEN", new Long(value1), new Long(value2), "appId");
            return this;
        }

        public Criteria andAppIdNotBetween(long value1, long value2) {
            addCriterion("APP_ID NOT BETWEEN", new Long(value1), new Long(value2), "appId");
            return this;
        }

        public Criteria andFunctionIdIsNull() {
            addCriterion("FUNCTION_ID IS NULL");
            return this;
        }

        public Criteria andFunctionIdIsNotNull() {
            addCriterion("FUNCTION_ID IS NOT NULL");
            return this;
        }

        public Criteria andFunctionIdEqualTo(long value) {
            addCriterion("FUNCTION_ID =", new Long(value), "functionId");
            return this;
        }

        public Criteria andFunctionIdNotEqualTo(long value) {
            addCriterion("FUNCTION_ID <>", new Long(value), "functionId");
            return this;
        }

        public Criteria andFunctionIdGreaterThan(long value) {
            addCriterion("FUNCTION_ID >", new Long(value), "functionId");
            return this;
        }

        public Criteria andFunctionIdGreaterThanOrEqualTo(long value) {
            addCriterion("FUNCTION_ID >=", new Long(value), "functionId");
            return this;
        }

        public Criteria andFunctionIdLessThan(long value) {
            addCriterion("FUNCTION_ID <", new Long(value), "functionId");
            return this;
        }

        public Criteria andFunctionIdLessThanOrEqualTo(long value) {
            addCriterion("FUNCTION_ID <=", new Long(value), "functionId");
            return this;
        }

        public Criteria andFunctionIdIn(long[] values) {
            addCriterion("FUNCTION_ID IN", values, "functionId");
            return this;
        }

        public Criteria andFunctionIdIn(List<Long> values) {
            addCriterion("FUNCTION_ID IN", values, "functionId");
            return this;
        }

        public Criteria andFunctionIdNotIn(long[] values) {
            addCriterion("FUNCTION_ID NOT IN", values, "functionId");
            return this;
        }

        public Criteria andFunctionIdNotIn(List<Long> values) {
            addCriterion("FUNCTION_ID NOT IN", values, "functionId");
            return this;
        }

        public Criteria andFunctionIdBetween(long value1, long value2) {
            addCriterion("FUNCTION_ID BETWEEN", new Long(value1), new Long(value2), "functionId");
            return this;
        }

        public Criteria andFunctionIdNotBetween(long value1, long value2) {
            addCriterion("FUNCTION_ID NOT BETWEEN", new Long(value1), new Long(value2), "functionId");
            return this;
        }

        public Criteria andOperateAppIdIsNull() {
            addCriterion("OPERATE_APP_ID IS NULL");
            return this;
        }

        public Criteria andOperateAppIdIsNotNull() {
            addCriterion("OPERATE_APP_ID IS NOT NULL");
            return this;
        }

        public Criteria andOperateAppIdEqualTo(Long value) {
            addCriterion("OPERATE_APP_ID =", value, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdNotEqualTo(Long value) {
            addCriterion("OPERATE_APP_ID <>", value, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdGreaterThan(Long value) {
            addCriterion("OPERATE_APP_ID >", value, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OPERATE_APP_ID >=", value, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdLessThan(Long value) {
            addCriterion("OPERATE_APP_ID <", value, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdLessThanOrEqualTo(Long value) {
            addCriterion("OPERATE_APP_ID <=", value, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdIn(Long[] values) {
            addCriterion("OPERATE_APP_ID IN", values, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdIn(List<Long> values) {
            addCriterion("OPERATE_APP_ID IN", values, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdNotIn(Long[] values) {
            addCriterion("OPERATE_APP_ID NOT IN", values, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdNotIn(List<Long> values) {
            addCriterion("OPERATE_APP_ID NOT IN", values, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdBetween(Long value1, Long value2) {
            addCriterion("OPERATE_APP_ID BETWEEN", value1, value2, "operateAppId");
            return this;
        }

        public Criteria andOperateAppIdNotBetween(Long value1, Long value2) {
            addCriterion("OPERATE_APP_ID NOT BETWEEN", value1, value2, "operateAppId");
            return this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("OPERATOR IS NULL");
            return this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("OPERATOR IS NOT NULL");
            return this;
        }

        public Criteria andOperatorEqualTo(Long value) {
            addCriterion("OPERATOR =", value, "operator");
            return this;
        }

        public Criteria andOperatorNotEqualTo(Long value) {
            addCriterion("OPERATOR <>", value, "operator");
            return this;
        }

        public Criteria andOperatorGreaterThan(Long value) {
            addCriterion("OPERATOR >", value, "operator");
            return this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("OPERATOR >=", value, "operator");
            return this;
        }

        public Criteria andOperatorLessThan(Long value) {
            addCriterion("OPERATOR <", value, "operator");
            return this;
        }

        public Criteria andOperatorLessThanOrEqualTo(Long value) {
            addCriterion("OPERATOR <=", value, "operator");
            return this;
        }

        public Criteria andOperatorIn(Long[] values) {
            addCriterion("OPERATOR IN", values, "operator");
            return this;
        }

        public Criteria andOperatorIn(List<Long> values) {
            addCriterion("OPERATOR IN", values, "operator");
            return this;
        }

        public Criteria andOperatorNotIn(Long[] values) {
            addCriterion("OPERATOR NOT IN", values, "operator");
            return this;
        }

        public Criteria andOperatorNotIn(List<Long> values) {
            addCriterion("OPERATOR NOT IN", values, "operator");
            return this;
        }

        public Criteria andOperatorBetween(Long value1, Long value2) {
            addCriterion("OPERATOR BETWEEN", value1, value2, "operator");
            return this;
        }

        public Criteria andOperatorNotBetween(Long value1, Long value2) {
            addCriterion("OPERATOR NOT BETWEEN", value1, value2, "operator");
            return this;
        }

        public Criteria andOperateTimeIsNull() {
            addCriterion("OPERATE_TIME IS NULL");
            return this;
        }

        public Criteria andOperateTimeIsNotNull() {
            addCriterion("OPERATE_TIME IS NOT NULL");
            return this;
        }

        public Criteria andOperateTimeEqualTo(Date value) {
            addCriterion("OPERATE_TIME =", value, "operateTime");
            return this;
        }

        public Criteria andOperateTimeNotEqualTo(Date value) {
            addCriterion("OPERATE_TIME <>", value, "operateTime");
            return this;
        }

        public Criteria andOperateTimeGreaterThan(Date value) {
            addCriterion("OPERATE_TIME >", value, "operateTime");
            return this;
        }

        public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERATE_TIME >=", value, "operateTime");
            return this;
        }

        public Criteria andOperateTimeLessThan(Date value) {
            addCriterion("OPERATE_TIME <", value, "operateTime");
            return this;
        }

        public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("OPERATE_TIME <=", value, "operateTime");
            return this;
        }

        public Criteria andOperateTimeIn(Date[] values) {
            addCriterion("OPERATE_TIME IN", values, "operateTime");
            return this;
        }

        public Criteria andOperateTimeIn(List<Date> values) {
            addCriterion("OPERATE_TIME IN", values, "operateTime");
            return this;
        }

        public Criteria andOperateTimeNotIn(Date[] values) {
            addCriterion("OPERATE_TIME NOT IN", values, "operateTime");
            return this;
        }

        public Criteria andOperateTimeNotIn(List<Date> values) {
            addCriterion("OPERATE_TIME NOT IN", values, "operateTime");
            return this;
        }

        public Criteria andOperateTimeBetween(Date value1, Date value2) {
            addCriterion("OPERATE_TIME BETWEEN", value1, value2, "operateTime");
            return this;
        }

        public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("OPERATE_TIME NOT BETWEEN", value1, value2, "operateTime");
            return this;
        }
    }
}