package com.afis.cloud.entities.model.auth;

import java.util.Date;

public class AppFunction {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_FUNCTION.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long id;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_FUNCTION.APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long appId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_FUNCTION.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long functionId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_FUNCTION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Long operateAppId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_FUNCTION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Long operator;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_FUNCTION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Date operateTime;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_A_APP_FUNCTION
     * @param appFunction
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void copy(AppFunction appFunction) {
        appFunction.id = this.id;
        appFunction.appId = this.appId;
        appFunction.functionId = this.functionId;
        appFunction.operateAppId = this.operateAppId;
        appFunction.operator = this.operator;
        appFunction.operateTime = this.operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_FUNCTION.ID
     *
     * @return the value of T_A_APP_FUNCTION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_FUNCTION.ID
     *
     * @param id the value for T_A_APP_FUNCTION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_FUNCTION.APP_ID
     *
     * @return the value of T_A_APP_FUNCTION.APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getAppId() {
        return appId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_FUNCTION.APP_ID
     *
     * @param appId the value for T_A_APP_FUNCTION.APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setAppId(long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_FUNCTION.FUNCTION_ID
     *
     * @return the value of T_A_APP_FUNCTION.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_FUNCTION.FUNCTION_ID
     *
     * @param functionId the value for T_A_APP_FUNCTION.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setFunctionId(long functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_FUNCTION.OPERATE_APP_ID
     *
     * @return the value of T_A_APP_FUNCTION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Long getOperateAppId() {
        return operateAppId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_FUNCTION.OPERATE_APP_ID
     *
     * @param operateAppId the value for T_A_APP_FUNCTION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateAppId(Long operateAppId) {
        this.operateAppId = operateAppId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_FUNCTION.OPERATOR
     *
     * @return the value of T_A_APP_FUNCTION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_FUNCTION.OPERATOR
     *
     * @param operator the value for T_A_APP_FUNCTION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_FUNCTION.OPERATE_TIME
     *
     * @return the value of T_A_APP_FUNCTION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_FUNCTION.OPERATE_TIME
     *
     * @param operateTime the value for T_A_APP_FUNCTION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder("{");
        sb.append("id:");
        sb.append(this.id);
        sb.append(", appId:");
        sb.append(this.appId);
        sb.append(", functionId:");
        sb.append(this.functionId);
        sb.append(", operateAppId:");
        sb.append(this.operateAppId);
        sb.append(", operator:");
        sb.append(this.operator);
        sb.append(", operateTime:");
        sb.append(this.operateTime);
        sb.append("}");
        return sb.toString();
    }
}