package com.afis.cloud.entities.model.auth;

import java.util.Date;

public class Application {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long id;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.APP_CODE
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String appCode;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.APP_NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String appName;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.KEY
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String key;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.URL_CALLBACK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String urlCallback;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.LOGO_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String logoPath;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String status;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String remark;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Long operateAppId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Long operator;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Date operateTime;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_A_APPLICATION
     * @param application
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void copy(Application application) {
        application.id = this.id;
        application.appCode = this.appCode;
        application.appName = this.appName;
        application.key = this.key;
        application.urlCallback = this.urlCallback;
        application.logoPath = this.logoPath;
        application.status = this.status;
        application.remark = this.remark;
        application.operateAppId = this.operateAppId;
        application.operator = this.operator;
        application.operateTime = this.operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.ID
     *
     * @return the value of T_A_APPLICATION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.ID
     *
     * @param id the value for T_A_APPLICATION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.APP_CODE
     *
     * @return the value of T_A_APPLICATION.APP_CODE
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.APP_CODE
     *
     * @param appCode the value for T_A_APPLICATION.APP_CODE
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.APP_NAME
     *
     * @return the value of T_A_APPLICATION.APP_NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.APP_NAME
     *
     * @param appName the value for T_A_APPLICATION.APP_NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.KEY
     *
     * @return the value of T_A_APPLICATION.KEY
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.KEY
     *
     * @param key the value for T_A_APPLICATION.KEY
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.URL_CALLBACK
     *
     * @return the value of T_A_APPLICATION.URL_CALLBACK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getUrlCallback() {
        return urlCallback;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.URL_CALLBACK
     *
     * @param urlCallback the value for T_A_APPLICATION.URL_CALLBACK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setUrlCallback(String urlCallback) {
        this.urlCallback = urlCallback;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.LOGO_PATH
     *
     * @return the value of T_A_APPLICATION.LOGO_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getLogoPath() {
        return logoPath;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.LOGO_PATH
     *
     * @param logoPath the value for T_A_APPLICATION.LOGO_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setLogoPath(String logoPath) {
        this.logoPath = logoPath;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.STATUS
     *
     * @return the value of T_A_APPLICATION.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.STATUS
     *
     * @param status the value for T_A_APPLICATION.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.REMARK
     *
     * @return the value of T_A_APPLICATION.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.REMARK
     *
     * @param remark the value for T_A_APPLICATION.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.OPERATE_APP_ID
     *
     * @return the value of T_A_APPLICATION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Long getOperateAppId() {
        return operateAppId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.OPERATE_APP_ID
     *
     * @param operateAppId the value for T_A_APPLICATION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateAppId(Long operateAppId) {
        this.operateAppId = operateAppId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.OPERATOR
     *
     * @return the value of T_A_APPLICATION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.OPERATOR
     *
     * @param operator the value for T_A_APPLICATION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.OPERATE_TIME
     *
     * @return the value of T_A_APPLICATION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.OPERATE_TIME
     *
     * @param operateTime the value for T_A_APPLICATION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder("{");
        sb.append("id:");
        sb.append(this.id);
        sb.append(", appCode:");
        sb.append(this.appCode);
        sb.append(", appName:");
        sb.append(this.appName);
        sb.append(", key:");
        sb.append(this.key);
        sb.append(", urlCallback:");
        sb.append(this.urlCallback);
        sb.append(", logoPath:");
        sb.append(this.logoPath);
        sb.append(", status:");
        sb.append(this.status);
        sb.append(", remark:");
        sb.append(this.remark);
        sb.append(", operateAppId:");
        sb.append(this.operateAppId);
        sb.append(", operator:");
        sb.append(this.operator);
        sb.append(", operateTime:");
        sb.append(this.operateTime);
        sb.append("}");
        return sb.toString();
    }
}