package com.afis.cloud.entities.model.auth;

import java.util.Date;

public class ApplicationSelective extends Application {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean id$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.APP_CODE
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean appCode$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.APP_NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean appName$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.KEY
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean key$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.URL_CALLBACK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean urlCallback$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.LOGO_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean logoPath$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean status$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean remark$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean operateAppId$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean operator$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APPLICATION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean operateTime$seted;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_A_APPLICATION
     * @param applicationSelective
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void copy(ApplicationSelective applicationSelective) {
        super.copy(applicationSelective);
        applicationSelective.id$seted = this.id$seted;
        applicationSelective.appCode$seted = this.appCode$seted;
        applicationSelective.appName$seted = this.appName$seted;
        applicationSelective.key$seted = this.key$seted;
        applicationSelective.urlCallback$seted = this.urlCallback$seted;
        applicationSelective.logoPath$seted = this.logoPath$seted;
        applicationSelective.status$seted = this.status$seted;
        applicationSelective.remark$seted = this.remark$seted;
        applicationSelective.operateAppId$seted = this.operateAppId$seted;
        applicationSelective.operator$seted = this.operator$seted;
        applicationSelective.operateTime$seted = this.operateTime$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.ID
     *
     * @return the value of T_A_APPLICATION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isId$seted() {
        return id$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.ID
     *
     * @param id the value for T_A_APPLICATION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id$seted = true;
        super.setId(id);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.APP_CODE
     *
     * @return the value of T_A_APPLICATION.APP_CODE
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isAppCode$seted() {
        return appCode$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.APP_CODE
     *
     * @param appCode the value for T_A_APPLICATION.APP_CODE
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setAppCode(String appCode) {
        this.appCode$seted = true;
        super.setAppCode(appCode);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.APP_NAME
     *
     * @return the value of T_A_APPLICATION.APP_NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isAppName$seted() {
        return appName$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.APP_NAME
     *
     * @param appName the value for T_A_APPLICATION.APP_NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setAppName(String appName) {
        this.appName$seted = true;
        super.setAppName(appName);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.KEY
     *
     * @return the value of T_A_APPLICATION.KEY
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isKey$seted() {
        return key$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.KEY
     *
     * @param key the value for T_A_APPLICATION.KEY
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setKey(String key) {
        this.key$seted = true;
        super.setKey(key);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.URL_CALLBACK
     *
     * @return the value of T_A_APPLICATION.URL_CALLBACK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isUrlCallback$seted() {
        return urlCallback$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.URL_CALLBACK
     *
     * @param urlCallback the value for T_A_APPLICATION.URL_CALLBACK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setUrlCallback(String urlCallback) {
        this.urlCallback$seted = true;
        super.setUrlCallback(urlCallback);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.LOGO_PATH
     *
     * @return the value of T_A_APPLICATION.LOGO_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isLogoPath$seted() {
        return logoPath$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.LOGO_PATH
     *
     * @param logoPath the value for T_A_APPLICATION.LOGO_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setLogoPath(String logoPath) {
        this.logoPath$seted = true;
        super.setLogoPath(logoPath);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.STATUS
     *
     * @return the value of T_A_APPLICATION.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isStatus$seted() {
        return status$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.STATUS
     *
     * @param status the value for T_A_APPLICATION.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setStatus(String status) {
        this.status$seted = true;
        super.setStatus(status);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.REMARK
     *
     * @return the value of T_A_APPLICATION.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isRemark$seted() {
        return remark$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.REMARK
     *
     * @param remark the value for T_A_APPLICATION.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setRemark(String remark) {
        this.remark$seted = true;
        super.setRemark(remark);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.OPERATE_APP_ID
     *
     * @return the value of T_A_APPLICATION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isOperateAppId$seted() {
        return operateAppId$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.OPERATE_APP_ID
     *
     * @param operateAppId the value for T_A_APPLICATION.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateAppId(Long operateAppId) {
        this.operateAppId$seted = true;
        super.setOperateAppId(operateAppId);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.OPERATOR
     *
     * @return the value of T_A_APPLICATION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isOperator$seted() {
        return operator$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.OPERATOR
     *
     * @param operator the value for T_A_APPLICATION.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperator(Long operator) {
        this.operator$seted = true;
        super.setOperator(operator);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APPLICATION.OPERATE_TIME
     *
     * @return the value of T_A_APPLICATION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isOperateTime$seted() {
        return operateTime$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APPLICATION.OPERATE_TIME
     *
     * @param operateTime the value for T_A_APPLICATION.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime$seted = true;
        super.setOperateTime(operateTime);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString().replaceAll("[}]$", ""));
        sb.append("}");
        return sb.toString();
    }
}