package com.afis.cloud.entities.model.auth;

import java.util.Date;

public class AppUserSelective extends AppUser {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean id$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.APP_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean appId$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.USER_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean userId$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.APP_PASSWORD
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean appPassword$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.WARRANT_PERMIT
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean warrantPermit$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.WARRANT
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean warrant$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean operateAppId$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.OPERATOR
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean operator$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_APP_USER.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    private boolean operateTime$seted;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_A_APP_USER
     * @param appUserSelective
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void copy(AppUserSelective appUserSelective) {
        super.copy(appUserSelective);
        appUserSelective.id$seted = this.id$seted;
        appUserSelective.appId$seted = this.appId$seted;
        appUserSelective.userId$seted = this.userId$seted;
        appUserSelective.appPassword$seted = this.appPassword$seted;
        appUserSelective.warrantPermit$seted = this.warrantPermit$seted;
        appUserSelective.warrant$seted = this.warrant$seted;
        appUserSelective.operateAppId$seted = this.operateAppId$seted;
        appUserSelective.operator$seted = this.operator$seted;
        appUserSelective.operateTime$seted = this.operateTime$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.ID
     *
     * @return the value of T_A_APP_USER.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isId$seted() {
        return id$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.ID
     *
     * @param id the value for T_A_APP_USER.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id$seted = true;
        super.setId(id);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.APP_ID
     *
     * @return the value of T_A_APP_USER.APP_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isAppId$seted() {
        return appId$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.APP_ID
     *
     * @param appId the value for T_A_APP_USER.APP_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setAppId(long appId) {
        this.appId$seted = true;
        super.setAppId(appId);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.USER_ID
     *
     * @return the value of T_A_APP_USER.USER_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isUserId$seted() {
        return userId$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.USER_ID
     *
     * @param userId the value for T_A_APP_USER.USER_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setUserId(long userId) {
        this.userId$seted = true;
        super.setUserId(userId);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.APP_PASSWORD
     *
     * @return the value of T_A_APP_USER.APP_PASSWORD
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isAppPassword$seted() {
        return appPassword$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.APP_PASSWORD
     *
     * @param appPassword the value for T_A_APP_USER.APP_PASSWORD
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setAppPassword(String appPassword) {
        this.appPassword$seted = true;
        super.setAppPassword(appPassword);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.WARRANT_PERMIT
     *
     * @return the value of T_A_APP_USER.WARRANT_PERMIT
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isWarrantPermit$seted() {
        return warrantPermit$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.WARRANT_PERMIT
     *
     * @param warrantPermit the value for T_A_APP_USER.WARRANT_PERMIT
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setWarrantPermit(String warrantPermit) {
        this.warrantPermit$seted = true;
        super.setWarrantPermit(warrantPermit);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.WARRANT
     *
     * @return the value of T_A_APP_USER.WARRANT
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isWarrant$seted() {
        return warrant$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.WARRANT
     *
     * @param warrant the value for T_A_APP_USER.WARRANT
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setWarrant(String warrant) {
        this.warrant$seted = true;
        super.setWarrant(warrant);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.OPERATE_APP_ID
     *
     * @return the value of T_A_APP_USER.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isOperateAppId$seted() {
        return operateAppId$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.OPERATE_APP_ID
     *
     * @param operateAppId the value for T_A_APP_USER.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setOperateAppId(Long operateAppId) {
        this.operateAppId$seted = true;
        super.setOperateAppId(operateAppId);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.OPERATOR
     *
     * @return the value of T_A_APP_USER.OPERATOR
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isOperator$seted() {
        return operator$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.OPERATOR
     *
     * @param operator the value for T_A_APP_USER.OPERATOR
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setOperator(Long operator) {
        this.operator$seted = true;
        super.setOperator(operator);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_APP_USER.OPERATE_TIME
     *
     * @return the value of T_A_APP_USER.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public boolean isOperateTime$seted() {
        return operateTime$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_APP_USER.OPERATE_TIME
     *
     * @param operateTime the value for T_A_APP_USER.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime$seted = true;
        super.setOperateTime(operateTime);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-11-08 16:49:54
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString().replaceAll("[}]$", ""));
        sb.append("}");
        return sb.toString();
    }
}