package com.afis.cloud.entities.model.auth;

public class FunctionSelective extends Function {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private boolean id$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.URL
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private boolean url$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private boolean name$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.TYPE
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private boolean type$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.REMARK
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private boolean remark$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.ORDER_NO
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private boolean orderNo$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.GROUP_NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private boolean groupName$seted;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_AI_FUNCTION
     * @param functionSelective
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void copy(FunctionSelective functionSelective) {
        super.copy(functionSelective);
        functionSelective.id$seted = this.id$seted;
        functionSelective.url$seted = this.url$seted;
        functionSelective.name$seted = this.name$seted;
        functionSelective.type$seted = this.type$seted;
        functionSelective.remark$seted = this.remark$seted;
        functionSelective.orderNo$seted = this.orderNo$seted;
        functionSelective.groupName$seted = this.groupName$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.ID
     *
     * @return the value of T_AI_FUNCTION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public boolean isId$seted() {
        return id$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.ID
     *
     * @param id the value for T_AI_FUNCTION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id$seted = true;
        super.setId(id);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.URL
     *
     * @return the value of T_AI_FUNCTION.URL
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public boolean isUrl$seted() {
        return url$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.URL
     *
     * @param url the value for T_AI_FUNCTION.URL
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setUrl(String url) {
        this.url$seted = true;
        super.setUrl(url);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.NAME
     *
     * @return the value of T_AI_FUNCTION.NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public boolean isName$seted() {
        return name$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.NAME
     *
     * @param name the value for T_AI_FUNCTION.NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setName(String name) {
        this.name$seted = true;
        super.setName(name);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.TYPE
     *
     * @return the value of T_AI_FUNCTION.TYPE
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public boolean isType$seted() {
        return type$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.TYPE
     *
     * @param type the value for T_AI_FUNCTION.TYPE
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setType(String type) {
        this.type$seted = true;
        super.setType(type);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.REMARK
     *
     * @return the value of T_AI_FUNCTION.REMARK
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public boolean isRemark$seted() {
        return remark$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.REMARK
     *
     * @param remark the value for T_AI_FUNCTION.REMARK
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setRemark(String remark) {
        this.remark$seted = true;
        super.setRemark(remark);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.ORDER_NO
     *
     * @return the value of T_AI_FUNCTION.ORDER_NO
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public boolean isOrderNo$seted() {
        return orderNo$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.ORDER_NO
     *
     * @param orderNo the value for T_AI_FUNCTION.ORDER_NO
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setOrderNo(long orderNo) {
        this.orderNo$seted = true;
        super.setOrderNo(orderNo);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.GROUP_NAME
     *
     * @return the value of T_AI_FUNCTION.GROUP_NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public boolean isGroupName$seted() {
        return groupName$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.GROUP_NAME
     *
     * @param groupName the value for T_AI_FUNCTION.GROUP_NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setGroupName(String groupName) {
        this.groupName$seted = true;
        super.setGroupName(groupName);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString().replaceAll("[}]$", ""));
        sb.append("}");
        return sb.toString();
    }
}