package com.afis.cloud.entities.model.auth;

public class Function {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private long id;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.URL
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private String url;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private String name;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.TYPE
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private String type;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.REMARK
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private String remark;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.ORDER_NO
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private long orderNo;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_FUNCTION.GROUP_NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    private String groupName;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_AI_FUNCTION
     * @param function
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void copy(Function function) {
        function.id = this.id;
        function.url = this.url;
        function.name = this.name;
        function.type = this.type;
        function.remark = this.remark;
        function.orderNo = this.orderNo;
        function.groupName = this.groupName;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.ID
     *
     * @return the value of T_AI_FUNCTION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.ID
     *
     * @param id the value for T_AI_FUNCTION.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.URL
     *
     * @return the value of T_AI_FUNCTION.URL
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.URL
     *
     * @param url the value for T_AI_FUNCTION.URL
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.NAME
     *
     * @return the value of T_AI_FUNCTION.NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.NAME
     *
     * @param name the value for T_AI_FUNCTION.NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.TYPE
     *
     * @return the value of T_AI_FUNCTION.TYPE
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.TYPE
     *
     * @param type the value for T_AI_FUNCTION.TYPE
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.REMARK
     *
     * @return the value of T_AI_FUNCTION.REMARK
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.REMARK
     *
     * @param remark the value for T_AI_FUNCTION.REMARK
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.ORDER_NO
     *
     * @return the value of T_AI_FUNCTION.ORDER_NO
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.ORDER_NO
     *
     * @param orderNo the value for T_AI_FUNCTION.ORDER_NO
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setOrderNo(long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_FUNCTION.GROUP_NAME
     *
     * @return the value of T_AI_FUNCTION.GROUP_NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_FUNCTION.GROUP_NAME
     *
     * @param groupName the value for T_AI_FUNCTION.GROUP_NAME
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-11-06 14:38:52
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder("{");
        sb.append("id:");
        sb.append(this.id);
        sb.append(", url:");
        sb.append(this.url);
        sb.append(", name:");
        sb.append(this.name);
        sb.append(", type:");
        sb.append(this.type);
        sb.append(", remark:");
        sb.append(this.remark);
        sb.append(", orderNo:");
        sb.append(this.orderNo);
        sb.append(", groupName:");
        sb.append(this.groupName);
        sb.append("}");
        return sb.toString();
    }
}