package com.afis.cloud.entities.model.auth;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

public class LoginLogExample {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private LinkedHashMap<String, String> orderByClauseMap;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String orderByClause;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected String alias;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample() {
        oredCriteria = new ArrayList<Criteria>();
        orderByClauseMap = new LinkedHashMap<String, String>();
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     * @param alias The dynamic alias of the table.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample(String alias) {
        this();
        this.alias = alias;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     * @param example Another example will be copied to this.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected LoginLogExample(LoginLogExample example) {
        this.orderByClauseMap = new LinkedHashMap<String, String>(example.orderByClauseMap);
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     * @param example Another example will be copied to this.
     * @param alias The dynamic alias of the table.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected LoginLogExample(LoginLogExample example, String alias) {
        this(example);
        this.alias = alias;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderById(String direction) {
        return this.orderBy("ID", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderById() {
        return this.removeOrderBy("ID");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderByUserId(String direction) {
        return this.orderBy("USER_ID", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByUserId() {
        return this.removeOrderBy("USER_ID");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderByLoginApp(String direction) {
        return this.orderBy("LOGIN_APP", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByLoginApp() {
        return this.removeOrderBy("LOGIN_APP");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderByLoginIp(String direction) {
        return this.orderBy("LOGIN_IP", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByLoginIp() {
        return this.removeOrderBy("LOGIN_IP");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderByStatus(String direction) {
        return this.orderBy("STATUS", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByStatus() {
        return this.removeOrderBy("STATUS");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderBySystemInfo(String direction) {
        return this.orderBy("SYSTEM_INFO", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderBySystemInfo() {
        return this.removeOrderBy("SYSTEM_INFO");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderByBrowserInfo(String direction) {
        return this.orderBy("BROWSER_INFO", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByBrowserInfo() {
        return this.removeOrderBy("BROWSER_INFO");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderByRemark(String direction) {
        return this.orderBy("REMARK", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByRemark() {
        return this.removeOrderBy("REMARK");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderByLoginTime(String direction) {
        return this.orderBy("LOGIN_TIME", direction);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderByLoginTime() {
        return this.removeOrderBy("LOGIN_TIME");
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public LoginLogExample orderBy(String field, String direction) {
        boolean have = orderByClauseMap.containsKey(field);
        String old = orderByClauseMap.put(field, direction);
        if(have && (old == null ? direction != null : !old.equals(direction))) orderByClause = null;
        return this;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String removeOrderBy(String field) {
        if(orderByClauseMap.containsKey(field)){
            orderByClause = null;
            return orderByClauseMap.remove(field);
        }
        return null;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void clearOrderByClause() {
        if(!orderByClauseMap.isEmpty()){
            orderByClause = null;
            orderByClauseMap.clear();
        }
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getOrderByClause() {
        if(orderByClause == null){
            StringBuilder sb = new StringBuilder();
            Iterator<Entry<String, String>> iterator = orderByClauseMap.entrySet().iterator();
            boolean aliasEmpty = this.alias == null || this.alias.isEmpty();
            while(iterator.hasNext()){
                Entry<String, String> entry = iterator.next();
                String key = entry.getKey();
                String value = entry.getValue();
                boolean keyEmpty = key == null || key.isEmpty();
                boolean valueEmpty = value == null || value.isEmpty();
                if(!keyEmpty){
                    if(!aliasEmpty){
                        sb.append(this.alias);
                        sb.append(".");
                    }
                    sb.append(entry.getKey());
                }
                if(!valueEmpty){
                    if(!keyEmpty) sb.append(" ");
                    sb.append(entry.getValue());
                }
                if(!keyEmpty || !valueEmpty) sb.append(", ");
            }
            if(sb.length() != 0) sb.setLength(sb.length() - 2);
            orderByClause = sb.toString();
        }
        return orderByClause;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     * @param alias The dynamic alias of the table.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setAlias(String alias) {
        this.alias = alias;
        orderByClause = null;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if(oredCriteria.size() == 0) oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    protected Criteria createCriteriaInternal() {
        return new Criteria();
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void clearOredCriteria() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by www.sacool.com iBATIS builder.
     * <br>This class corresponds to the database table T_A_LOGIN_LOG
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public static class Criteria {
        protected List<String> criteriaWithSqlSnippetValue;

        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithSqlSnippetValue = new ArrayList<String>();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithSqlSnippetValue.size() > 0
                || criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithSqlSnippetValue() {
            return criteriaWithSqlSnippetValue;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            List<Map<String, Object>> list = null;
            String valueKey = "value";
            if(value.getClass().isArray()) {
                if(Array.getLength(value) == 0) throw new RuntimeException("Value array for " + property + " cannot be empty");
                list = criteriaWithListValue;
                valueKey = "values";
            } else list = criteriaWithSingleValue;
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put(valueKey, value);
            list.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSQLSnippet(String sqlSnippet) {
            if(sqlSnippet == null){
                throw new RuntimeException("Value for sqlSnippet cannot be null");
            }
            criteriaWithSqlSnippetValue.add(sqlSnippet);
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID IS NULL");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID IS NOT NULL");
            return this;
        }

        public Criteria andIdEqualTo(long value) {
            addCriterion("ID =", new Long(value), "id");
            return this;
        }

        public Criteria andIdNotEqualTo(long value) {
            addCriterion("ID <>", new Long(value), "id");
            return this;
        }

        public Criteria andIdGreaterThan(long value) {
            addCriterion("ID >", new Long(value), "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(long value) {
            addCriterion("ID >=", new Long(value), "id");
            return this;
        }

        public Criteria andIdLessThan(long value) {
            addCriterion("ID <", new Long(value), "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(long value) {
            addCriterion("ID <=", new Long(value), "id");
            return this;
        }

        public Criteria andIdIn(long[] values) {
            addCriterion("ID IN", values, "id");
            return this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID IN", values, "id");
            return this;
        }

        public Criteria andIdNotIn(long[] values) {
            addCriterion("ID NOT IN", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID NOT IN", values, "id");
            return this;
        }

        public Criteria andIdBetween(long value1, long value2) {
            addCriterion("ID BETWEEN", new Long(value1), new Long(value2), "id");
            return this;
        }

        public Criteria andIdNotBetween(long value1, long value2) {
            addCriterion("ID NOT BETWEEN", new Long(value1), new Long(value2), "id");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID IS NULL");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID IS NOT NULL");
            return this;
        }

        public Criteria andUserIdEqualTo(long value) {
            addCriterion("USER_ID =", new Long(value), "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(long value) {
            addCriterion("USER_ID <>", new Long(value), "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(long value) {
            addCriterion("USER_ID >", new Long(value), "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(long value) {
            addCriterion("USER_ID >=", new Long(value), "userId");
            return this;
        }

        public Criteria andUserIdLessThan(long value) {
            addCriterion("USER_ID <", new Long(value), "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(long value) {
            addCriterion("USER_ID <=", new Long(value), "userId");
            return this;
        }

        public Criteria andUserIdIn(long[] values) {
            addCriterion("USER_ID IN", values, "userId");
            return this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("USER_ID IN", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(long[] values) {
            addCriterion("USER_ID NOT IN", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("USER_ID NOT IN", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(long value1, long value2) {
            addCriterion("USER_ID BETWEEN", new Long(value1), new Long(value2), "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(long value1, long value2) {
            addCriterion("USER_ID NOT BETWEEN", new Long(value1), new Long(value2), "userId");
            return this;
        }

        public Criteria andLoginAppIsNull() {
            addCriterion("LOGIN_APP IS NULL");
            return this;
        }

        public Criteria andLoginAppIsNotNull() {
            addCriterion("LOGIN_APP IS NOT NULL");
            return this;
        }

        public Criteria andLoginAppEqualTo(long value) {
            addCriterion("LOGIN_APP =", new Long(value), "loginApp");
            return this;
        }

        public Criteria andLoginAppNotEqualTo(long value) {
            addCriterion("LOGIN_APP <>", new Long(value), "loginApp");
            return this;
        }

        public Criteria andLoginAppGreaterThan(long value) {
            addCriterion("LOGIN_APP >", new Long(value), "loginApp");
            return this;
        }

        public Criteria andLoginAppGreaterThanOrEqualTo(long value) {
            addCriterion("LOGIN_APP >=", new Long(value), "loginApp");
            return this;
        }

        public Criteria andLoginAppLessThan(long value) {
            addCriterion("LOGIN_APP <", new Long(value), "loginApp");
            return this;
        }

        public Criteria andLoginAppLessThanOrEqualTo(long value) {
            addCriterion("LOGIN_APP <=", new Long(value), "loginApp");
            return this;
        }

        public Criteria andLoginAppIn(long[] values) {
            addCriterion("LOGIN_APP IN", values, "loginApp");
            return this;
        }

        public Criteria andLoginAppIn(List<Long> values) {
            addCriterion("LOGIN_APP IN", values, "loginApp");
            return this;
        }

        public Criteria andLoginAppNotIn(long[] values) {
            addCriterion("LOGIN_APP NOT IN", values, "loginApp");
            return this;
        }

        public Criteria andLoginAppNotIn(List<Long> values) {
            addCriterion("LOGIN_APP NOT IN", values, "loginApp");
            return this;
        }

        public Criteria andLoginAppBetween(long value1, long value2) {
            addCriterion("LOGIN_APP BETWEEN", new Long(value1), new Long(value2), "loginApp");
            return this;
        }

        public Criteria andLoginAppNotBetween(long value1, long value2) {
            addCriterion("LOGIN_APP NOT BETWEEN", new Long(value1), new Long(value2), "loginApp");
            return this;
        }

        public Criteria andLoginIpIsNull() {
            addCriterion("LOGIN_IP IS NULL");
            return this;
        }

        public Criteria andLoginIpIsNotNull() {
            addCriterion("LOGIN_IP IS NOT NULL");
            return this;
        }

        public Criteria andLoginIpEqualTo(String value) {
            addCriterion("LOGIN_IP =", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotEqualTo(String value) {
            addCriterion("LOGIN_IP <>", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpGreaterThan(String value) {
            addCriterion("LOGIN_IP >", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_IP >=", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpLessThan(String value) {
            addCriterion("LOGIN_IP <", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_IP <=", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpLike(String value) {
            addCriterion("LOGIN_IP LIKE", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotLike(String value) {
            addCriterion("LOGIN_IP NOT LIKE", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpIn(String[] values) {
            addCriterion("LOGIN_IP IN", values, "loginIp");
            return this;
        }

        public Criteria andLoginIpIn(List<String> values) {
            addCriterion("LOGIN_IP IN", values, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotIn(String[] values) {
            addCriterion("LOGIN_IP NOT IN", values, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotIn(List<String> values) {
            addCriterion("LOGIN_IP NOT IN", values, "loginIp");
            return this;
        }

        public Criteria andLoginIpBetween(String value1, String value2) {
            addCriterion("LOGIN_IP BETWEEN", value1, value2, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotBetween(String value1, String value2) {
            addCriterion("LOGIN_IP NOT BETWEEN", value1, value2, "loginIp");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS IS NULL");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS IS NOT NULL");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS LIKE", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS NOT LIKE", value, "status");
            return this;
        }

        public Criteria andStatusIn(String[] values) {
            addCriterion("STATUS IN", values, "status");
            return this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS IN", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(String[] values) {
            addCriterion("STATUS NOT IN", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS NOT IN", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS BETWEEN", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS NOT BETWEEN", value1, value2, "status");
            return this;
        }

        public Criteria andSystemInfoIsNull() {
            addCriterion("SYSTEM_INFO IS NULL");
            return this;
        }

        public Criteria andSystemInfoIsNotNull() {
            addCriterion("SYSTEM_INFO IS NOT NULL");
            return this;
        }

        public Criteria andSystemInfoEqualTo(String value) {
            addCriterion("SYSTEM_INFO =", value, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoNotEqualTo(String value) {
            addCriterion("SYSTEM_INFO <>", value, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoGreaterThan(String value) {
            addCriterion("SYSTEM_INFO >", value, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEM_INFO >=", value, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoLessThan(String value) {
            addCriterion("SYSTEM_INFO <", value, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoLessThanOrEqualTo(String value) {
            addCriterion("SYSTEM_INFO <=", value, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoLike(String value) {
            addCriterion("SYSTEM_INFO LIKE", value, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoNotLike(String value) {
            addCriterion("SYSTEM_INFO NOT LIKE", value, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoIn(String[] values) {
            addCriterion("SYSTEM_INFO IN", values, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoIn(List<String> values) {
            addCriterion("SYSTEM_INFO IN", values, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoNotIn(String[] values) {
            addCriterion("SYSTEM_INFO NOT IN", values, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoNotIn(List<String> values) {
            addCriterion("SYSTEM_INFO NOT IN", values, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoBetween(String value1, String value2) {
            addCriterion("SYSTEM_INFO BETWEEN", value1, value2, "systemInfo");
            return this;
        }

        public Criteria andSystemInfoNotBetween(String value1, String value2) {
            addCriterion("SYSTEM_INFO NOT BETWEEN", value1, value2, "systemInfo");
            return this;
        }

        public Criteria andBrowserInfoIsNull() {
            addCriterion("BROWSER_INFO IS NULL");
            return this;
        }

        public Criteria andBrowserInfoIsNotNull() {
            addCriterion("BROWSER_INFO IS NOT NULL");
            return this;
        }

        public Criteria andBrowserInfoEqualTo(String value) {
            addCriterion("BROWSER_INFO =", value, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoNotEqualTo(String value) {
            addCriterion("BROWSER_INFO <>", value, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoGreaterThan(String value) {
            addCriterion("BROWSER_INFO >", value, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoGreaterThanOrEqualTo(String value) {
            addCriterion("BROWSER_INFO >=", value, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoLessThan(String value) {
            addCriterion("BROWSER_INFO <", value, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoLessThanOrEqualTo(String value) {
            addCriterion("BROWSER_INFO <=", value, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoLike(String value) {
            addCriterion("BROWSER_INFO LIKE", value, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoNotLike(String value) {
            addCriterion("BROWSER_INFO NOT LIKE", value, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoIn(String[] values) {
            addCriterion("BROWSER_INFO IN", values, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoIn(List<String> values) {
            addCriterion("BROWSER_INFO IN", values, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoNotIn(String[] values) {
            addCriterion("BROWSER_INFO NOT IN", values, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoNotIn(List<String> values) {
            addCriterion("BROWSER_INFO NOT IN", values, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoBetween(String value1, String value2) {
            addCriterion("BROWSER_INFO BETWEEN", value1, value2, "browserInfo");
            return this;
        }

        public Criteria andBrowserInfoNotBetween(String value1, String value2) {
            addCriterion("BROWSER_INFO NOT BETWEEN", value1, value2, "browserInfo");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK IS NULL");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK IS NOT NULL");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK LIKE", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK NOT LIKE", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(String[] values) {
            addCriterion("REMARK IN", values, "remark");
            return this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK IN", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(String[] values) {
            addCriterion("REMARK NOT IN", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK NOT IN", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK BETWEEN", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK NOT BETWEEN", value1, value2, "remark");
            return this;
        }

        public Criteria andLoginTimeIsNull() {
            addCriterion("LOGIN_TIME IS NULL");
            return this;
        }

        public Criteria andLoginTimeIsNotNull() {
            addCriterion("LOGIN_TIME IS NOT NULL");
            return this;
        }

        public Criteria andLoginTimeEqualTo(Date value) {
            addCriterion("LOGIN_TIME =", value, "loginTime");
            return this;
        }

        public Criteria andLoginTimeNotEqualTo(Date value) {
            addCriterion("LOGIN_TIME <>", value, "loginTime");
            return this;
        }

        public Criteria andLoginTimeGreaterThan(Date value) {
            addCriterion("LOGIN_TIME >", value, "loginTime");
            return this;
        }

        public Criteria andLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LOGIN_TIME >=", value, "loginTime");
            return this;
        }

        public Criteria andLoginTimeLessThan(Date value) {
            addCriterion("LOGIN_TIME <", value, "loginTime");
            return this;
        }

        public Criteria andLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("LOGIN_TIME <=", value, "loginTime");
            return this;
        }

        public Criteria andLoginTimeIn(Date[] values) {
            addCriterion("LOGIN_TIME IN", values, "loginTime");
            return this;
        }

        public Criteria andLoginTimeIn(List<Date> values) {
            addCriterion("LOGIN_TIME IN", values, "loginTime");
            return this;
        }

        public Criteria andLoginTimeNotIn(Date[] values) {
            addCriterion("LOGIN_TIME NOT IN", values, "loginTime");
            return this;
        }

        public Criteria andLoginTimeNotIn(List<Date> values) {
            addCriterion("LOGIN_TIME NOT IN", values, "loginTime");
            return this;
        }

        public Criteria andLoginTimeBetween(Date value1, Date value2) {
            addCriterion("LOGIN_TIME BETWEEN", value1, value2, "loginTime");
            return this;
        }

        public Criteria andLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("LOGIN_TIME NOT BETWEEN", value1, value2, "loginTime");
            return this;
        }
    }
}