package com.afis.cloud.entities.model.auth;

public class Menu {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_MENU.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long id;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_MENU.NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String name;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_MENU.ICON_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String iconPath;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_MENU.PARENT_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long parentId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_MENU.ORDERED
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long ordered;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_MENU.MENU_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String menuPath;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_AI_MENU.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String remark;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_AI_MENU
     * @param menu
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void copy(Menu menu) {
        menu.id = this.id;
        menu.name = this.name;
        menu.iconPath = this.iconPath;
        menu.parentId = this.parentId;
        menu.ordered = this.ordered;
        menu.menuPath = this.menuPath;
        menu.remark = this.remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_MENU.ID
     *
     * @return the value of T_AI_MENU.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_MENU.ID
     *
     * @param id the value for T_AI_MENU.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_MENU.NAME
     *
     * @return the value of T_AI_MENU.NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_MENU.NAME
     *
     * @param name the value for T_AI_MENU.NAME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_MENU.ICON_PATH
     *
     * @return the value of T_AI_MENU.ICON_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_MENU.ICON_PATH
     *
     * @param iconPath the value for T_AI_MENU.ICON_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_MENU.PARENT_ID
     *
     * @return the value of T_AI_MENU.PARENT_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_MENU.PARENT_ID
     *
     * @param parentId the value for T_AI_MENU.PARENT_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_MENU.ORDERED
     *
     * @return the value of T_AI_MENU.ORDERED
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getOrdered() {
        return ordered;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_MENU.ORDERED
     *
     * @param ordered the value for T_AI_MENU.ORDERED
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOrdered(long ordered) {
        this.ordered = ordered;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_MENU.MENU_PATH
     *
     * @return the value of T_AI_MENU.MENU_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_MENU.MENU_PATH
     *
     * @param menuPath the value for T_AI_MENU.MENU_PATH
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_AI_MENU.REMARK
     *
     * @return the value of T_AI_MENU.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_AI_MENU.REMARK
     *
     * @param remark the value for T_AI_MENU.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder("{");
        sb.append("id:");
        sb.append(this.id);
        sb.append(", name:");
        sb.append(this.name);
        sb.append(", iconPath:");
        sb.append(this.iconPath);
        sb.append(", parentId:");
        sb.append(this.parentId);
        sb.append(", ordered:");
        sb.append(this.ordered);
        sb.append(", menuPath:");
        sb.append(this.menuPath);
        sb.append(", remark:");
        sb.append(this.remark);
        sb.append("}");
        return sb.toString();
    }
}