package com.afis.cloud.entities.model.auth;

import java.util.Date;

public class OnlineUser {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_ONLINE_USER.LOGIN_KEY
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    private String loginKey;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_ONLINE_USER.USER_ID
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    private long userId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_ONLINE_USER.LOGIN_TIME
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    private Date loginTime;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_A_ONLINE_USER
     * @param onlineUser
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public void copy(OnlineUser onlineUser) {
        onlineUser.loginKey = this.loginKey;
        onlineUser.userId = this.userId;
        onlineUser.loginTime = this.loginTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_ONLINE_USER.LOGIN_KEY
     *
     * @return the value of T_A_ONLINE_USER.LOGIN_KEY Primary Key
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public String getLoginKey() {
        return loginKey;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_ONLINE_USER.LOGIN_KEY
     *
     * @param loginKey the value for T_A_ONLINE_USER.LOGIN_KEY Primary Key
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public void setLoginKey(String loginKey) {
        this.loginKey = loginKey;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_ONLINE_USER.USER_ID
     *
     * @return the value of T_A_ONLINE_USER.USER_ID
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public long getUserId() {
        return userId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_ONLINE_USER.USER_ID
     *
     * @param userId the value for T_A_ONLINE_USER.USER_ID
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_ONLINE_USER.LOGIN_TIME
     *
     * @return the value of T_A_ONLINE_USER.LOGIN_TIME
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_ONLINE_USER.LOGIN_TIME
     *
     * @param loginTime the value for T_A_ONLINE_USER.LOGIN_TIME
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-11-22 11:14:33
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder("{");
        sb.append("loginKey:");
        sb.append(this.loginKey);
        sb.append(", userId:");
        sb.append(this.userId);
        sb.append(", loginTime:");
        sb.append(this.loginTime);
        sb.append("}");
        return sb.toString();
    }
}