package com.afis.cloud.entities.model.auth;

import java.util.Date;

public class OperateLog {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long id;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private long functionId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.LOGIN_IP
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String loginIp;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String status;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private String remark;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Long operateAppId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Long operator;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private Date operateTime;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_A_OPERATE_LOG
     * @param operateLog
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void copy(OperateLog operateLog) {
        operateLog.id = this.id;
        operateLog.functionId = this.functionId;
        operateLog.loginIp = this.loginIp;
        operateLog.status = this.status;
        operateLog.remark = this.remark;
        operateLog.operateAppId = this.operateAppId;
        operateLog.operator = this.operator;
        operateLog.operateTime = this.operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.ID
     *
     * @return the value of T_A_OPERATE_LOG.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.ID
     *
     * @param id the value for T_A_OPERATE_LOG.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @return the value of T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public long getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @param functionId the value for T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setFunctionId(long functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.LOGIN_IP
     *
     * @return the value of T_A_OPERATE_LOG.LOGIN_IP
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.LOGIN_IP
     *
     * @param loginIp the value for T_A_OPERATE_LOG.LOGIN_IP
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.STATUS
     *
     * @return the value of T_A_OPERATE_LOG.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.STATUS
     *
     * @param status the value for T_A_OPERATE_LOG.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.REMARK
     *
     * @return the value of T_A_OPERATE_LOG.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.REMARK
     *
     * @param remark the value for T_A_OPERATE_LOG.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @return the value of T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Long getOperateAppId() {
        return operateAppId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @param operateAppId the value for T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateAppId(Long operateAppId) {
        this.operateAppId = operateAppId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.OPERATOR
     *
     * @return the value of T_A_OPERATE_LOG.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.OPERATOR
     *
     * @param operator the value for T_A_OPERATE_LOG.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @return the value of T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @param operateTime the value for T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder("{");
        sb.append("id:");
        sb.append(this.id);
        sb.append(", functionId:");
        sb.append(this.functionId);
        sb.append(", loginIp:");
        sb.append(this.loginIp);
        sb.append(", status:");
        sb.append(this.status);
        sb.append(", remark:");
        sb.append(this.remark);
        sb.append(", operateAppId:");
        sb.append(this.operateAppId);
        sb.append(", operator:");
        sb.append(this.operator);
        sb.append(", operateTime:");
        sb.append(this.operateTime);
        sb.append("}");
        return sb.toString();
    }
}