package com.afis.cloud.entities.model.auth;

import java.util.Date;

public class OperateLogSelective extends OperateLog {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean id$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean functionId$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.LOGIN_IP
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean loginIp$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean status$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean remark$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean operateAppId$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean operator$seted;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    private boolean operateTime$seted;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_A_OPERATE_LOG
     * @param operateLogSelective
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void copy(OperateLogSelective operateLogSelective) {
        super.copy(operateLogSelective);
        operateLogSelective.id$seted = this.id$seted;
        operateLogSelective.functionId$seted = this.functionId$seted;
        operateLogSelective.loginIp$seted = this.loginIp$seted;
        operateLogSelective.status$seted = this.status$seted;
        operateLogSelective.remark$seted = this.remark$seted;
        operateLogSelective.operateAppId$seted = this.operateAppId$seted;
        operateLogSelective.operator$seted = this.operator$seted;
        operateLogSelective.operateTime$seted = this.operateTime$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.ID
     *
     * @return the value of T_A_OPERATE_LOG.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isId$seted() {
        return id$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.ID
     *
     * @param id the value for T_A_OPERATE_LOG.ID Primary Key
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id$seted = true;
        super.setId(id);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @return the value of T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isFunctionId$seted() {
        return functionId$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @param functionId the value for T_A_OPERATE_LOG.FUNCTION_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setFunctionId(long functionId) {
        this.functionId$seted = true;
        super.setFunctionId(functionId);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.LOGIN_IP
     *
     * @return the value of T_A_OPERATE_LOG.LOGIN_IP
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isLoginIp$seted() {
        return loginIp$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.LOGIN_IP
     *
     * @param loginIp the value for T_A_OPERATE_LOG.LOGIN_IP
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setLoginIp(String loginIp) {
        this.loginIp$seted = true;
        super.setLoginIp(loginIp);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.STATUS
     *
     * @return the value of T_A_OPERATE_LOG.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isStatus$seted() {
        return status$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.STATUS
     *
     * @param status the value for T_A_OPERATE_LOG.STATUS
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setStatus(String status) {
        this.status$seted = true;
        super.setStatus(status);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.REMARK
     *
     * @return the value of T_A_OPERATE_LOG.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isRemark$seted() {
        return remark$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.REMARK
     *
     * @param remark the value for T_A_OPERATE_LOG.REMARK
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setRemark(String remark) {
        this.remark$seted = true;
        super.setRemark(remark);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @return the value of T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isOperateAppId$seted() {
        return operateAppId$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @param operateAppId the value for T_A_OPERATE_LOG.OPERATE_APP_ID
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateAppId(Long operateAppId) {
        this.operateAppId$seted = true;
        super.setOperateAppId(operateAppId);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.OPERATOR
     *
     * @return the value of T_A_OPERATE_LOG.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isOperator$seted() {
        return operator$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.OPERATOR
     *
     * @param operator the value for T_A_OPERATE_LOG.OPERATOR
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperator(Long operator) {
        this.operator$seted = true;
        super.setOperator(operator);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @return the value of T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public boolean isOperateTime$seted() {
        return operateTime$seted;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @param operateTime the value for T_A_OPERATE_LOG.OPERATE_TIME
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime$seted = true;
        super.setOperateTime(operateTime);
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2018-10-31 11:01:44
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString().replaceAll("[}]$", ""));
        sb.append("}");
        return sb.toString();
    }
}